# Generated by Django 5.1.5 on 2025-03-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamland_app', '0008_property_property_owner_name_alter_property_bhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact number', max_length=15, null=True),
        ),
    ]
